# Generated by Django 2.2 on 2019-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_question_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a desination name (e.g. Peniche etc)', max_length=200)),
            ],
        ),
    ]
