# Generated by Django 2.2 on 2019-05-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the persona (e.g. First timer etc)', max_length=200)),
                ('desination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.Destination')),
            ],
        ),
    ]
