# Generated by Django 2.2 on 2019-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='desination',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='persona',
            name='description',
            field=models.CharField(help_text='Enter a description for the persona (e.g. Wants to surf for the first time etc)', max_length=200, null=True),
        ),
    ]
