# Generated by Django 2.2 on 2019-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0007_auto_20190508_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='answer',
            field=models.ManyToManyField(help_text='Select the answers that indicate that this destination is right', to='wizard.Answer'),
        ),
    ]
