# Generated by Django 2.2 on 2019-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0008_destination_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='answer',
        ),
        migrations.AddField(
            model_name='persona',
            name='answer',
            field=models.ManyToManyField(help_text='Select the answers that indicates this persona', to='wizard.Answer'),
        ),
    ]
