# Generated by Django 2.2 on 2019-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0010_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='destination_image'),
        ),
    ]
