# Generated by Django 2.2 on 2019-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0012_auto_20190511_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='main_images'),
        ),
    ]
