# Generated by Django 2.2 on 2019-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0013_destination_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(upload_to='main_images'),
        ),
    ]
