# Generated by Django 2.2 on 2019-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0014_auto_20190523_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='long_description',
            field=models.TextField(default='No long description has yet been written for this destination', help_text='Enter a longer description for this destination', max_length=2000),
        ),
    ]
