# Generated by Django 2.2 on 2019-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0016_bulletpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
            ],
        ),
    ]
