# Generated by Django 2.2 on 2019-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0018_auto_20190527_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='iframe_map',
            field=models.CharField(default='None', help_text='Paste google maps embedd code here', max_length=200),
        ),
    ]
