# Generated by Django 2.2 on 2019-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0019_destination_iframe_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='iframe_map',
            field=models.CharField(default='None', help_text="Paste google maps embedd code here or 'None' if empty", max_length=500),
        ),
    ]
