# Generated by Django 2.2 on 2019-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0021_auto_20190527_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbbackup', models.FileField(upload_to='all_db_backups')),
                ('comment', models.CharField(help_text='Enter a comment', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='iframe_map',
            field=models.URLField(default='maps.google.com', help_text="Paste google maps embedd code here or 'None' if empty", max_length=500),
        ),
    ]
